services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:{create,migrate} && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/fetch-take-home
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - FETCH-TAKE-HOME_DATABASE_HOSTNAME=db
      - FETCH-TAKE-HOME_DATABASE_PASSWORD=password
      - FETCH-TAKE-HOME_DATABASE_USERNAME=postgres
