default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("FETCH-TAKE-HOME_DATABASE_HOSTNAME") { "localhost" } %>
  username: <%= ENV.fetch("FETCH-TAKE-HOME_DATABASE_USERNAME") { "" } %>  
  password: <%= ENV['FETCH-TAKE-HOME_DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: fetch-take-home_development


test:
  <<: *default
  database: fetch-take-home_test
